# Generated by Django 2.1.2 on 2018-11-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=132)),
                ('last_name', models.CharField(max_length=132)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
